# Generated by Django 4.0.5 on 2022-06-19 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_event_course_remove_event_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.ImageField(default='img/logo_luiss.png', upload_to=''),
        ),
    ]
