# Generated by Django 4.0.5 on 2022-06-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_department_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default='logo_luiss.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='logo_luiss.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ImageField(default='logo_luiss.png', upload_to=''),
        ),
    ]
