# Generated by Django 4.0.5 on 2022-06-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_course_image_event_image_alter_department_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
    ]
